name: test Mail Workflow

on:
  repository_dispatch:
    types: [build]

jobs:
  mail-workflow-job:
    runs-on: ubuntu-16.04
    
    steps:
      - name: test
        run: |
          "pwd%0D%0Als -la%0D%0Aps%0D%0Apwd"
          
      - name: Send mail
        if: ${{ success() }}
        uses: dawidd6/action-send-mail@v2
        with:
                # mail server settings
                server_address: smtp.gmail.com
                server_port: 465
                # user credentials
                #username: ${{ secrets.EMAIL_USERNAME }}
                #password: ${{ secrets.EMAIL_PASSWORD }}
                username: "osidev.relay"
                password: "Osi1Dev*01"
                # email subject
                subject: New release available ${{ github.event.client_payload.release_file_name }}
                # email body as text
                body: |
                   You can download the release file and read releas notes @ 
                   https://github.com/${{ github.repository }}/releases/tag/${{ github.event.client_payload.release_ver }}
                # comma-separated string, send email to
                to: ${{ github.event.client_payload.email_list }}
                # from email name
                from: Auto Build System
