name: test workflow

on:
  repository_dispatch:
    types: [build]


jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{ github.event.client_payload.device_type }}
        run: echo ${{ github.event.client_payload.release_ver }}
      - name: Run shell commands
        run: |
          pwd
          ls -la
          ps aux
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          echo git$github:$GITHUB_REPOSITORY
          # git clone git$github:$GITHUB_REPOSITORY
      #- name: Show file contents
      #  run: cat 
